-- Years of NFL experience, which Sleeper has always published and this app has
-- never stored.
--
-- Wanted for one specific measurement: whether a manager reaches for rookies.
-- The brief for league behaviour asks for "rookie preference" as an
-- evidence-backed tendency, and without this column it is permanently
-- unmeasurable -- the transaction record says which player was added and the
-- player table could not say how old his career was.
--
-- Nullable, and null means the dictionary did not say. A missing value is
-- excluded from the tendency's sample rather than counted as a veteran, which
-- would make every league of unsynced players look rookie-averse.
ALTER TABLE players ADD COLUMN years_exp INTEGER;
