/**
 * Draws the Home Screen icon set from a fixed 32x32 pixel-art grid.
 *
 * STALE as of the "The Junculator" artwork: the committed icons in
 * src/web/public/ (icon-192.png, icon-512.png, icon-maskable-512.png,
 * apple-touch-icon.png, favicon.svg) were generated by resizing a supplied
 * illustration directly, not by this grid. Running this script will
 * overwrite them with the old Yoshi-sprite pixel art below — don't run it
 * unless that's actually what's wanted. See git history for that art, and
 * for the diamond mark before it, if either is ever wanted back.
 *
 * Kept as a worked example of building a Home Screen icon set (including
 * the maskable safe-zone padding and the from-scratch PNG/SVG encoders)
 * for the next time the artwork is grid-based pixel art instead of a photo
 * or illustration:
 *
 *   node scripts/make-icons.mjs
 *
 * It exists rather than a checked-in binary blob with no provenance,
 * because "where did this PNG come from and how do I make a 512 one" is a
 * question that otherwise has no answer. No image library is involved — a
 * PNG is a zlib stream of filtered scanlines, and node ships zlib. The SVG
 * favicon is written the same way, as one <rect> per grid cell.
 */

import { deflateSync } from 'node:zlib';
import { writeFileSync, mkdirSync } from 'node:fs';
import { join } from 'node:path';
import { fileURLToPath } from 'node:url';

const OUT = fileURLToPath(new URL('../src/web/public/', import.meta.url));

/* -- the artwork ------------------------------------------------------------
 * One letter per 32x32 cell, row-major, sampled from the source sprite at
 * its native grid resolution. */

const PALETTE = {
  A: [255, 235, 59], // page yellow (background)
  B: [0, 0, 0], // outline
  C: [100, 221, 23], // body, light green
  D: [51, 105, 30], // body, dark green (shading)
  E: [104, 159, 56], // body, mid green (shading)
  F: [255, 255, 255], // belly / eye / shoe highlights
  G: [255, 152, 0], // shell spikes, orange
  H: [198, 40, 40], // saddle, red
};

const GRID = [
  'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA',
  'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA',
  'AAAAAAAAAAAAAAAAAABBAAAAAAAAAAAA',
  'AAAAAAAAAAAAAAAAABCDBAAAAAAAAAAA',
  'AAAAAAAAAAAAAAAABEDFFBAAAAAAAAAA',
  'AAAAAAAAAAAAAAAABDFFBBAAAAAAAAAA',
  'AAAAAAAAAAAAAABBBFFFBBBBBAAAAAAA',
  'AAAAAAAAAAAAABGGBFFFFBCCCBBAAAAA',
  'AAAAAAAAAAAAABGGBDFFDCCCFFCBAAAA',
  'AAAAAAAAAAAAAABBBEDDCCCCCBFBAAAA',
  'AAAAAAAAAAAAABGBDEECCCCCCCCCBAAA',
  'AAAAAAAAAAAAABGBDECCCCECCCCCBAAA',
  'AAAAAAAAAAAAAABBDECCCFBECCCCBAAA',
  'AAAAAAAAAAAAAABGBECCCFBECCCCBAAA',
  'AAAAAAAAAAAAAABGBECCFBBDECCEBAAA',
  'AAAAAAAAAAAAAABBBEFFFFFBDEEBAAAA',
  'AAAAAAAAAAAAABGBDEFFBFFFBBBAAAAA',
  'AAAAAAAAAAAAAABBEEFBABBBAAAAAAAA',
  'AAAAAABBBBBBBBBDCFBAAAAAAAAAAAAA',
  'AAAABBFBHGGFBFBCFFBAAAAAAAAAAAAA',
  'AAABEBFBHHHGBFBFFFBAAAAAAAAAAAAA',
  'AAAABFBFBBBBFBFFFFBAAAAAAAAAAAAA',
  'AAAABFBFFFFFBBBFFFBAAAAAAAAAAAAA',
  'AAAABFFBBBBBBCBBBBBAAAAAAAAAAAAA',
  'AAAAABFBFEEEBCCBCCBAAAAAAAAAAAAA',
  'AAAAABFBBBBBBBCCCCBAAAAAAAAAAAAA',
  'AAAAABFBHHHHHBBCCBAAAAAAAAAAAAAA',
  'AAAAAABBHHHHHFBBBAAAAAAAAAAAAAAA',
  'AAAAAAABHHHHHHBAAAAAAAAAAAAAAAAA',
  'AAAAAAABBBBBBBBAAAAAAAAAAAAAAAAA',
  'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA',
  'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA',
];

const N = GRID.length; // 32

function cellColour(gx, gy) {
  return PALETTE[GRID[gy][gx]];
}

/**
 * Rasterises the grid into an RGBA buffer of `size` x `size` pixels.
 * `scale` shrinks the artwork toward the centre (padded with the
 * background colour) — used for the maskable icon, whose safe zone is the
 * middle ~80% of the canvas.
 */
function draw(size, scale = 1) {
  const px = Buffer.alloc(size * size * 4);
  const bg = PALETTE.A;
  const cell = (size * scale) / N;
  const offset = (size - size * scale) / 2;
  for (let py = 0; py < size; py++) {
    for (let pxi = 0; pxi < size; pxi++) {
      const gx = Math.floor((pxi - offset) / cell);
      const gy = Math.floor((py - offset) / cell);
      const inBounds = gx >= 0 && gx < N && gy >= 0 && gy < N;
      const rgb = inBounds ? cellColour(gx, gy) : bg;
      const i = (py * size + pxi) * 4;
      px[i] = rgb[0];
      px[i + 1] = rgb[1];
      px[i + 2] = rgb[2];
      px[i + 3] = 255;
    }
  }
  return px;
}

/* -- the PNG container ----------------------------------------------------- */

const CRC_TABLE = Array.from({ length: 256 }, (_, n) => {
  let c = n;
  for (let k = 0; k < 8; k++) c = c & 1 ? 0xedb88320 ^ (c >>> 1) : c >>> 1;
  return c >>> 0;
});

function crc32(buf) {
  let c = 0xffffffff;
  for (const byte of buf) c = CRC_TABLE[(c ^ byte) & 0xff] ^ (c >>> 8);
  return (c ^ 0xffffffff) >>> 0;
}

function chunk(type, data) {
  const length = Buffer.alloc(4);
  length.writeUInt32BE(data.length);
  const body = Buffer.concat([Buffer.from(type, 'latin1'), data]);
  const crc = Buffer.alloc(4);
  crc.writeUInt32BE(crc32(body));
  return Buffer.concat([length, body, crc]);
}

function png(size, rgba) {
  const ihdr = Buffer.alloc(13);
  ihdr.writeUInt32BE(size, 0);
  ihdr.writeUInt32BE(size, 4);
  ihdr[8] = 8; // bit depth
  ihdr[9] = 6; // truecolour with alpha
  // Every scanline is prefixed with its filter type; 0 (none) keeps this
  // readable, and the flat regions compress away regardless.
  const raw = Buffer.alloc(size * (size * 4 + 1));
  for (let y = 0; y < size; y++) {
    raw[y * (size * 4 + 1)] = 0;
    rgba.copy(raw, y * (size * 4 + 1) + 1, y * size * 4, (y + 1) * size * 4);
  }
  return Buffer.concat([
    Buffer.from([0x89, 0x50, 0x4e, 0x47, 0x0d, 0x0a, 0x1a, 0x0a]),
    chunk('IHDR', ihdr),
    chunk('IDAT', deflateSync(raw, { level: 9 })),
    chunk('IEND', Buffer.alloc(0)),
  ]);
}

/* -- the SVG favicon --------------------------------------------------------
 * One <rect> per grid cell, run-length encoded per row so the file stays
 * readable instead of 1024 individual rects. */

function svg() {
  const rows = [];
  for (let gy = 0; gy < N; gy++) {
    let x = 0;
    while (x < N) {
      const key = GRID[gy][x];
      let runEnd = x + 1;
      while (runEnd < N && GRID[gy][runEnd] === key) runEnd++;
      if (key !== 'A') {
        const [r, g, b] = PALETTE[key];
        const hex = [r, g, b].map((v) => v.toString(16).padStart(2, '0')).join('');
        rows.push(`<rect x="${x}" y="${gy}" width="${runEnd - x}" height="1" fill="#${hex}" />`);
      }
      x = runEnd;
    }
  }
  const [br, bg, bb] = PALETTE.A;
  const bgHex = [br, bg, bb].map((v) => v.toString(16).padStart(2, '0')).join('');
  return `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 ${N} ${N}" role="img" aria-label="Fantasy Analyst">
  <rect width="${N}" height="${N}" fill="#${bgHex}" />
  ${rows.join('\n  ')}
</svg>
`;
}

/* -- the set --------------------------------------------------------------- */

const ICONS = [
  { file: 'icon-192.png', size: 192, scale: 1 },
  { file: 'icon-512.png', size: 512, scale: 1 },
  // Maskable: the artwork stays inside the safe circle, so a platform that
  // crops to a circle or a squircle never clips it.
  { file: 'icon-maskable-512.png', size: 512, scale: 0.8 },
  // iOS uses this one for the Home Screen and rounds the corners itself.
  { file: 'apple-touch-icon.png', size: 180, scale: 1 },
];

mkdirSync(OUT, { recursive: true });
for (const { file, size, scale } of ICONS) {
  const bytes = png(size, draw(size, scale));
  writeFileSync(join(OUT, file), bytes);
  console.log(`${file.padEnd(24)} ${size}×${size}  ${(bytes.length / 1024).toFixed(1)} kB`);
}

const svgBytes = svg();
writeFileSync(join(OUT, 'favicon.svg'), svgBytes);
console.log(`favicon.svg              ${N}×${N}  ${(svgBytes.length / 1024).toFixed(1)} kB`);
